
console.log(__filename.slice(__dirname.length + 1) + ' START')

exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('matches_teams_players').del(),
	knex('matches_teams_players').insert({match_id: 1, player_id: 1, team_id: 1, number: 1, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 2, team_id: 1, number: 5, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 3, team_id: 1, number: 7, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 4, team_id: 1, number: 8, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 5, team_id: 1, number: 2, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 6, team_id: 1, number: 10, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 7, team_id: 1, number: 9, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 8, team_id: 1, number: 3, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 9, team_id: 1, number: 11, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 10, team_id: 1, number: 4, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 11, team_id: 2, number: 13, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 12, team_id: 2, number: 7, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 13, team_id: 2, number: 3, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 14, team_id: 2, number: 2, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 15, team_id: 2, number: 5, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 16, team_id: 2, number: 17, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 17, team_id: 2, number: 1, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 18, team_id: 2, number: 8, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 19, team_id: 2, number: 5, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 20, team_id: 2, number: 99, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 21, team_id: 2, number: 9, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 1, player_id: 22, team_id: 2, number: 10, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:23, team_id: 3, number:13, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:24, team_id: 3, number:7, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:25, team_id: 3, number:3, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:26, team_id: 3, number:2, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:27, team_id: 3, number:5, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:28, team_id: 3, number:17, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:29, team_id: 3, number:1, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:30, team_id: 3, number:8, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:31, team_id: 3, number:5, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:32, team_id: 3, number:99, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:33, team_id: 3, number:9, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:34, team_id: 3, number:10, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:35, team_id: 4, number:4, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:36, team_id: 4, number:5, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:37, team_id: 4, number:1, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:38, team_id: 4, number:8, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:39, team_id: 4, number:6, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:40, team_id: 4, number:9, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:41, team_id: 4, number:2, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:42, team_id: 4, number:7, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:43, team_id: 4, number:3, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:44, team_id: 4, number:10, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 2, player_id:45, team_id: 4, number:11, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:1, team_id: 1, number: 1, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:2, team_id: 1, number: 5, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:3, team_id: 1, number: 7, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:4, team_id: 1, number: 8, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:5, team_id: 1, number: 2, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:6, team_id: 1, number: 10, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:7, team_id: 1, number: 9, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:8, team_id: 1, number: 3, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:9, team_id: 1, number: 11, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:10, team_id: 1, number: 4, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:35, team_id: 4, number: 4, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:36, team_id: 4, number: 5, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:37, team_id: 4, number: 1, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:38, team_id: 4, number: 8, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:39, team_id: 4, number: 6, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:40, team_id: 4, number: 9, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:41, team_id: 4, number: 2, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:42, team_id: 4, number: 7, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:43, team_id: 4, number: 3, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:44, team_id: 4, number: 10, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 3, player_id:45, team_id: 4, number: 11, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:11, team_id: 2, number: 13, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:12, team_id: 2, number: 7, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:13, team_id: 2, number: 3, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:14, team_id: 2, number: 2, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:15, team_id: 2, number: 5, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:16, team_id: 2, number: 17, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:17, team_id: 2, number: 1, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:18, team_id: 2, number: 8, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:19, team_id: 2, number: 5, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:20, team_id: 2, number: 99, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:21, team_id: 2, number: 9, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:22, team_id: 2, number: 10, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:23, team_id: 3, number: 13, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:24, team_id: 3, number: 7, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:25, team_id: 3, number: 3, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:26, team_id: 3, number: 2, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:27, team_id: 3, number: 5, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:28, team_id: 3, number: 17, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:29, team_id: 3, number: 1, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:30, team_id: 3, number: 8, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:31, team_id: 3, number: 5, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:32, team_id: 3, number: 99, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:33, team_id: 3, number: 9, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 4, player_id:34, team_id: 3, number: 10, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:1, team_id: 1, number: 1, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:2, team_id: 1, number: 5, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:3, team_id: 1, number: 7, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:4, team_id: 1, number: 8, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:5, team_id: 1, number: 2, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:6, team_id: 1, number: 10, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:7, team_id: 1, number: 9, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:8, team_id: 1, number: 3, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:9, team_id: 1, number: 11, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:10, team_id: 1, number: 4, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:23, team_id: 3, number: 3, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:24, team_id: 3, number: 7, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:25, team_id: 3, number: 3, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:26, team_id: 3, number: 2, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:27, team_id: 3, number: 5, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:28, team_id: 3, number: 7, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:29, team_id: 3, number: 1, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:30, team_id: 3, number: 8, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:31, team_id: 3, number: 5, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:32, team_id: 3, number: 99, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:33, team_id: 3, number: 9, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 5, player_id:34, team_id: 3, number: 10, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:11, team_id: 2, number: 13, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:12, team_id: 2, number: 7, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:13, team_id: 2, number: 3, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:14, team_id: 2, number: 2, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:15, team_id: 2, number: 5, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:16, team_id: 2, number: 17, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:17, team_id: 2, number: 1, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:18, team_id: 2, number: 8, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:19, team_id: 2, number: 5, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:20, team_id: 2, number: 9, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:21, team_id: 2, number: 9, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:22, team_id: 2, number: 10, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:35, team_id: 4, number: 4, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:36, team_id: 4, number: 5, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:37, team_id: 4, number: 1, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:38, team_id: 4, number: 8, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:39, team_id: 4, number: 6, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:40, team_id: 4, number: 9, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:41, team_id: 4, number: 2, position: 'D'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:42, team_id: 4, number: 7, position: 'P'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:43, team_id: 4, number: 3, position: 'DEL'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:44, team_id: 4, number: 10, position: 'M'}),
	knex('matches_teams_players').insert({match_id: 6, player_id:45, team_id: 4, number: 11, position: 'D'})

    )
};

console.log(__filename.slice(__dirname.length + 1) + ' OK')
